name: Build Trick App
on: push

jobs:
  build:
    name: Build Trick App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List Files in Dir
        run: ls
      - name: Check Dotnet Cli
        run: dotnet build
      - name: List Files in Dir
        run: ls TrickingLibrary.Api/ -R
      - name: Check NPM Cli
        run: npm --version
     